// import { barbequemasala } from "";

export const PRODUCTS = [
  {
    id: 1,
    src: require("./../../assets/images/barbeque-masala.png"),
    name: "Barbeque Masala",
    quantity: "500gm",
    ingredients: "not known",
    isAvailable: true,
    price: 368,
  },
  {
    id: 2,
    src: require("./../../assets/images/Ginger-Garlic.png"),
    name: "Ginger Garlic Paste",
    quantity: "500gm",
    ingredients: "ginger, garlic, salt",
    isAvailable: true,
    price: 331,
  },
  {
    id: 3,
    src: require("./../../assets/images/Ginger-Paste.png"),
    name: "Ginger Paste",
    quantity: "500gm",
    ingredients: "ginger, garlic, salt",
    isAvailable: true,
    price: 300,
  },
  {
    id: 4,
    src: require("./../../assets/images/Chinese-Schezwan-Sauce.png"),
    name: "Schezwan Sauce",
    quantity: "500gm",
    ingredients: "red chilli, water, salt, vinegar,ginger,garlic",
    isAvailable: true,
    price: 331,
  },
  {
    id: 5,
    src: "https://rukminim2.flixcart.com/image/416/416/xif0q/spice-masala/t/4/v/250-chilli-paste-3x-spicy-instant-cooking-paste-250gm-glass-original-imagwak8unhnwjzc.jpeg?q=70&crop=false",
    name: "Chilly Paste",
    quantity: "250gm",
    ingredients: "not known",
    isAvailable: true,
    price: 330,
  },
  {
    id: 6,
    src: require("./../../assets/images/Chilli-Paste.png"),
    name: "Chilly Paste",
    quantity: "500gm",
    ingredients: "red chilli, water, salt, vinegar,ginger,garlic",
    isAvailable: true,
    price: 609,
  },
  {
    id: 7,
    src: require("./../../assets/images/Shezwan-Chutney.png"),
    name: "Schezwan Chutney",
    quantity: "250gm",
    ingredients: "red chilli, water, salt, vinegar,ginger,garlic",
    isAvailable: true,
    price: 437,
  },
  {
    id: 8,
    src: require("./../../assets/images/Chilli-Garlic_.png"),
    name: "Chilli Garlic Paste",
    quantity: "250gm",
    ingredients: "red chilli, water, salt, vinegar,ginger,garlic",
    isAvailable: true,
    price: 465,
  },
  {
    id: 9,
    src: require("./../../assets/images/Chinese-Chilli-Oil.png"),
    name: "Chilli Oil",
    quantity: "500gm",
    ingredients:
      "red chilli, rich sunflower oil, water, salt, vinegar,ginger,garlic",
    isAvailable: true,
    price: 465,
  },
  {
    id: 10,
    src: require("./../../assets/images/Dal-Rasoi_.png"),
    name: "Dal Rasoi",
    quantity: "250gm",
    ingredients: "not known",
    isAvailable: true,
    price: 268,
  },
  {
    id: 11,
    src: require("./../../assets/images/Fish-Masala.png"),
    name: "Fish Masala",
    quantity: "500gm",
    ingredients: "not known",
    isAvailable: true,
    price: 338,
  },
  {
    id: 12,
    src: require("./../../assets/images/Garlic-Pickle.png"),
    name: "Garlic Pickle",
    quantity: "500gm",
    ingredients: "garlic, vinegar, salt, sugar",
    isAvailable: true,
    price: 458,
  },
  {
    id: 13,
    src: require("./../../assets/images/Kabab-Masala.png"),
    name: "Kabab Masala",
    quantity: "500gm",
    ingredients: "garlic, vinegar, salt, sugar",
    isAvailable: true,
    price: 423,
  },
  {
    id: 14,
    src: require("./../../assets/images/Korian-Chilli.png"),
    name: "Korian Chilli",
    quantity: "500gm",
    ingredients: "not know",
    isAvailable: true,
    price: 685,
  },
  {
    id: 15,
    src: require("./../../assets/images/Mixed-Mango-Pickle_.png"),
    name: "Mixed Mango Pickle",
    quantity: "500gm",
    ingredients: "raw mango, vinegar, salt, sugar",
    isAvailable: true,
    price: 575,
  },
  {
    id: 16,
    src: require("./../../assets/images/Mango-Pickle.png"),
    name: "Mango Pickle",
    quantity: "500gm",
    ingredients: "raw mango, vinegar, salt, sugar",
    isAvailable: true,
    price: 595,
  },
  {
    id: 17,
    src: require("./../../assets/images/Premium-Schezwan_.png"),
    name: "Premium Schezwan Chutney",
    quantity: "500gm",
    ingredients: "red chilli, water, salt, vinegar, chilly flakes, ginger,garlic",
    isAvailable: true,
    price: 825,
  },
];
